### ISSUE TITLE
Test compile with PGI compilers

### ISSUE THREAD

**Issue by theavey** [jprov410/mqds#3]
It would be good to test compilation of the program using Portland Group compilers as they're commonly used.

[This repository](https://github.com/nemequ/pgi-travis) seems like a useful tool for this.

**Comment by jprov410** [comment]
Great idea, Thomas! I will implement this to test PGI compilation.

**Comment by theavey** [comment]
Seems like the script can be run more specifically doing something more like [this](https://docs.travis-ci.com/user/customizing-the-build/#Implementing-Complex-Build-Steps).

**Comment by theavey** [comment]
Something like this should work:
```bash
if [[ "$FC" == "pgf90" ]]
    then
        wget -q -O /dev/stdout \
        'https://raw.githubusercontent.com/nemequ/pgi-travis/master/install-pgi.sh' | \
        /bin/sh
fi
```

**Comment by jprov410** [comment]
Thank you,  Thomas. This helped a lot!
